// PWA Service Worker - Generated by it.adi.p Automator
const CACHE_NAME = 'pwa_pro-cache-v1777132027500';
const ASSETS = ["./","./index.html","./manifest.json"];

self.addEventListener('install', (event) => {
    self.skipWaiting();
    event.waitUntil(
        caches.open(CACHE_NAME).then((cache) => {
            console.log('PWA: Caching Assets');
            return cache.addAll(ASSETS);
        })
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys().then((keys) => Promise.all(
            keys.map((k) => {
                if (k !== CACHE_NAME) {
                    console.log('PWA: Cleaning Old Cache', k);
                    return caches.delete(k);
                }
            })
        ))
    );
    return self.clients.claim();
});

self.addEventListener('fetch', (event) => {
    // Network First strategy for dynamic updates, fallback to cache
    event.respondWith(
        fetch(event.request).catch(() => caches.match(event.request))
    );
});